import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './Components/Header/Header';
import Footer from './Components/Footer/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import { FirebaseProvider } from './context/Firebase';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GuFu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen w-full flex flex-col">
          <Header />
          <FirebaseProvider>{children}</FirebaseProvider>
          <Footer />
        </main>
      </body>
    </html>
  );
}
